---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: services-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "SESSION"
    nginx.ingress.kubernetes.io/load-balance: "round_robin"

spec:
  rules:
    - http:
        paths:
          - path: /pi/?(.*)
            backend:
              serviceName: pi
              servicePort: 8082
          - path: /streamer/?(.*)
            backend:
              serviceName: streamer
              servicePort: 8083
          - path: /ws/?(.*)
            backend:
              serviceName: ws
              servicePort: 8084
          - path: /?(.*)
            backend:
              serviceName: ui
              servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/load-balance: "round_robin"
spec:
  rules:
    - http:
        paths:
          - path: /auth/?(.*)
            backend:
              serviceName: auth
              servicePort: 9999
